Contrast-Security-OSS/contrast-sdk-java

pom.xml, src/main/java/com/contrastsecurity/models/CodeObject.java, src/main/java/com/contrastsecurity/models/Server.java, src/main/java/com/contrastsecurity/utils/ContrastSDKUtils.java
This includes a fix for the base 64 not working in Bamboo and the new Server environments breaking our conversion from JSON to POJO.
=> Base64 fix and Server environments fix

src/main/java/com/contrastsecurity/http/UrlBuilder.java, src/main/java/com/contrastsecurity/sdk/ContrastSDK.java, src/main/java/com/contrastsecurity/utils/ContrastSDKUtils.java, src/test/java/com/contrastsecurity/ContrastSDKTest.java, src/test/java/com/contrastsecurity/UrlBuilderTest.java
Added the endpoint for /ng/{orgUuid}/applications/name and the request getApplicationsNames to retrieve only the names of the applications. Added to minimize the length of the response when only the name of the application is needed.
=> Application name endpoint

src/main/java/com/contrastsecurity/exceptions/ApplicationCreateException.java, src/main/java/com/contrastsecurity/http/MediaType.java, src/main/java/com/contrastsecurity/http/UrlBuilder.java, src/main/java/com/contrastsecurity/models/dtm/ApplicationCreateRequest.java, src/main/java/com/contrastsecurity/sdk/ContrastSDK.java, src/test/java/com/contrastsecurity/UrlBuilderTest.java
In the case of the contrast jenkins plugin. We need to be able to link a jenkins job to an application that has not yet been instrumented. This is to prevent the user from having to configure their jobs twice, once before the application has been instrumented and again after the application has been instrumented.
In order to link the application and the jenkins job before the application is instrumented we need to first create the application then return the application id to jenkins. The agent endpoint for creating an application poses two issues:
* It requires the application to be linked to an existing server.
* It does not return the application id.
* The response is massive
We are creating an endpoint to be used by integrations for creating an application and return information that …
=> Contrast-38919 add create app method

src/main/java/com/contrastsecurity/http/UrlBuilder.java, src/main/java/com/contrastsecurity/models/dtm/ApplicationCreateRequest.java, src/main/java/com/contrastsecurity/sdk/ContrastSDK.java, src/test/java/com/contrastsecurity/UrlBuilderTest.java
Unable to get an already existing application without the APP ID
Create a method that accepts an application's name, language, and org to find a matching application
Added a method to get an application based on name, language, and org
=> CONTRAST-38919-add-get-app-by-name-and-language

src/main/java/com/contrastsecurity/http/UrlBuilder.java, src/main/java/com/contrastsecurity/models/AgentType.java, src/test/java/com/contrastsecurity/UrlBuilderTest.java
CONTRAST-38919
Sdk's AgentType enum is missing some agents. So the user cannot specify a language they see in contrast but sdk does not support.
Add missing AgentTypes.
1. Added missing agent types to AgentType enum
1. add agentUrl
=> Contrast 38919 add agent types

src/main/java/com/contrastsecurity/http/SecurityCheckForm.java, src/main/java/com/contrastsecurity/http/SecurityCheckResponse.java, src/main/java/com/contrastsecurity/http/UrlBuilder.java, src/main/java/com/contrastsecurity/models/JobOutcomePolicy.java, src/main/java/com/contrastsecurity/models/SecurityCheck.java, src/main/java/com/contrastsecurity/sdk/ContrastSDK.java, src/test/java/com/contrastsecurity/ContrastSDKTest.java, src/test/java/com/contrastsecurity/UrlBuilderTest.java
https://bitbucket.org/contrastsecurity/teamserver/pull-requests/9772/contrast-39403-calculate-security-check/diff
New changes were made in the server api
Update the sdk to be able to make a security check
* Added a new makeRequestWithBody to ContrastSDK to be able to make a request with a body
* Added SecurityCheckResponse as a wrapper to handle the security check response
* Updated JobOutcomePolicy fields.
* Updated SecurityCheck fields.
* Updated makeSecurityCheck method.
1. make a security check for an application that is supposed to pass.
1. verify that security check fields are populated properly.
1. verify that the security check result is true and job outcome policy is null.
1. make a security check for an application that is supposed to fail.
1. verify that the security check …
=> Contrast 39403 update sdk for new security check

src/main/java/com/contrastsecurity/models/SecurityCheck.java
Need to know if no policy is defined for application
* Made result nullable, meaning security check was not run because no policy is defined for the application.
=> Contrast security check result

src/main/java/com/contrastsecurity/http/SecurityCheckForm.java
https://bitbucket.org/contrastsecurity/teamserver/pull-requests/9871/contrast-39402-add-support-for-app-id-in
Add application id to security check form to allow identifying application using application id.
Sometimes a user may only have the application id with no reliable way to get the application's original name and language. To solve this, we are adding the ability for the user to identify the application they would like to perform a security check against using the application's id.
* Added applicationId to SecurityCheckForm
* Created two constructors for SecurityCheckForm
* One for applicationId
* Another for applicationName and agentLanguage
* This only allows an instance of SecurityCheckForm to be created with either the applicationId, or the applicationName and agentLanguage …
=> Add application id to security check to allow identifying the application

src/main/java/com/contrastsecurity/http/JobOutcomePolicyListResponse.java, src/main/java/com/contrastsecurity/http/UrlBuilder.java, src/main/java/com/contrastsecurity/sdk/ContrastSDK.java, src/test/java/com/contrastsecurity/ContrastSDKTest.java, src/test/java/com/contrastsecurity/UrlBuilderTest.java
https://bitbucket.org/contrastsecurity/teamserver/pull-requests/10016
Add methods for getting enabled job outcome policies and enabled job outcome policies that apply to a specific application
These methods are needed by the Jenkins plugin.
=> Contrast 39516 add get enabled policies

README.md, src/main/java/com/contrastsecurity/sdk/ContrastSDK.java
Implemented a builder pattern to combat too many parameters to constructors.
Marked constructors as deprecated to encourage use of the builder.
=> Contrast 39999 add constructor with proxy default api url

pom.xml, src/main/java/com/contrastsecurity/http/ApplicationFilterForm.java, src/main/java/com/contrastsecurity/http/UrlBuilder.java, src/main/java/com/contrastsecurity/sdk/ContrastSDK.java, src/test/java/com/contrastsecurity/ApplicationFilterFilterFormTest.java, src/test/java/com/contrastsecurity/ContrastSDKTest.java, src/test/java/com/contrastsecurity/FilterFormTest.java, src/test/java/com/contrastsecurity/ScreenerTest.java, src/test/java/com/contrastsecurity/UrlBuilderTest.java
As a user of the Contrast Java SDK I'd like to be able to use a method to call the following endpoint -> `/ng/{orgUuid}/applications/filter`.
I added a ScreenerTest to verify and did manual testing with the endpoint.
=> CUST-2645 - Added ApplicationFilter Endpoint

pom.xml
The lombok dependency should always use `<scope>provided</scope>` in a Maven project, because it is not a dependency users need at runtime. Rather, this project only needs Lombok at compile time to use its annotation processor.
=> 👷 JAVA-3136 Migrate Lombok from Runtime Dependency to Compile Only

pom.xml, src/main/java/com/contrastsecurity/models/CodeObject.java
Contrast SDK includes JAXB as a compile time dependency. Since JAXB was included in JDKs prior to JDK 11, this is a problematic dependency to force our users to take. It’s very likely to cause conflicts that users will have to deconflict using tedious Maven and Gradle configuration.
We only use JAXB for a base64 utility. The method that uses the utility always throws `NullPointerException`. The class to which this method belongs was drafted 7 years ago and never used. Marking it as deprecating.
=> 🔥 JAVA-3132 Remove JAXB Dependency

.github/workflows/publish.yml, pom.xml
This updates the jdk version to 11 for the publish step so that we can run the spotless test in the publish workflow
=> Spotless check for publish

pom.xml, src/main/java/com/contrastsecurity/utils/ContrastSDKUtils.java
Use standard library instead of `commons-codec` which drops a dependency.
Since the library is supported on JDK 8 or newer this should be ok to do.
=> Use java.util.Base64 instead of commons-codec

.github/workflows/build.yml
Changed on push trigger to only trigger on the main branch. Pull request still triggers on all.
This allows the build to trigger when a pull request from a forked repo is opened and prevents duplicate triggers on our pull request.
down side is that pushing to feature branches doesn't trigger the build action. I think this is fine. Verification is only needed when you are ready to merge.
=> Prevent Duplicate Trigger but still allow pull requests from forked repositories to be verified.

pom.xml
* Configures [maven-enforcer-plugin](https://maven.apache.org/enforcer/enforcer-rules/index.html) to enforce good practices.
* Use explicit versions for all plugins (defined in `pluginManagement`).
* Remove parent pom with old deployment workflow - we use the `release` profile and the `nexus-staging-maven-plugin` now.
=> ♻️ JAVA-3298 Clean-Up Maven POM

.github/workflows/build.yml, pom.xml
Use javac `--release` flag to cross compile to Java 1.8 from Java 15.
Unlike the `-source` and `-target` compiler flags we were using, the `--release` flag ensures that we only use APIs available in JDK 1.8 despite compiling with JDK 15. Likewise, compiling with JDK 15 ensures that we don't depend on an API that's been removed since JDK 1.8 (e.g. JAXB).
This helps us catch incompatibilities earlier vs running JDK 1.8, 11, and 15 in the pipeline. My take is that this change obviates the need to re-run tests in JDK 1.8, 11, and 15.
=> 👷 JAVA-3298 Cross Compile With Release Flag

pom.xml, src/test/java/com/contrastsecurity/ApplicationFilterFilterFormTest.java, src/test/java/com/contrastsecurity/ContrastSDKTest.java, src/test/java/com/contrastsecurity/FilterFormTest.java, src/test/java/com/contrastsecurity/ScreenerTest.java, src/test/java/com/contrastsecurity/UrlBuilderTest.java
Upgrading to JUnit 5 before proposing a new test suite for verifying API interaction. Consistent with the Java Team style guide, migrate assertions to use [AssertJ](https://assertj.github.io/doc/)
=> ⬆️ JAVA-3298 Migrate to JUnit 5

src/main/java/com/contrastsecurity/http/LibraryFilterForm.java, src/main/java/com/contrastsecurity/http/UrlBuilder.java, src/main/java/com/contrastsecurity/sdk/ContrastSDK.java
This adds support for the following APIs:
* `/ng/{orgUid}/libraries`
* `/ng/{orgUid}/libraries/filter`
* `/ng/{orgUid}/applications/{appId}/libraries/filter`
=> Add support for organization and application libraries filter APIs

src/main/java/com/contrastsecurity/models/Library.java
When expanding `apps` in library responses (see #87) the API returns the servers for the libraries.
Enable serializing the servers in the responses.
=> Add support for servers in library reponses

pom.xml, src/main/java/com/contrastsecurity/http/ApplicationFilterForm.java, src/main/java/com/contrastsecurity/http/FilterForm.java, src/main/java/com/contrastsecurity/http/LibraryFilterForm.java, src/main/java/com/contrastsecurity/http/ServerFilterForm.java, src/main/java/com/contrastsecurity/http/TraceFilterForm.java, src/main/java/com/contrastsecurity/sdk/ContrastSDK.java, src/main/java/com/contrastsecurity/utils/ContrastSDKUtils.java, src/test/java/com/contrastsecurity/ScreenerTest.java
To remain a lightweight library, we aim to use very few dependencies in the Contrast Java SDK. To this end, this change removes the Apache Commons libraries in favor of utilities built into JDK 1.8. Also, this change removes the unused slf4j-api dependency.
=> 🔥 JAVA-3298 Remove Utility Dependencies

README.md, pom.xml
Replace the Maven POM XML sample (that easily becomes out of date) with a badge where users can find the latest version on Maven Central.
=> 📝 JAVA-3292 Include Maven Central badge in README

gradle-plugin/build.gradle, gradle-plugin/src/main/java/com/contrastsecurity/gradle/plugin/ContrastGradlePlugin.java
Verify Test Tasks were being marked as `UP-TO-DATE` and not running if they passed once. Even running `clean` wouldn't cause them to rerun. Fixed by forcing this task to never be up to date. This is good anyway because we want to re-query the sdk every time we run tests or change the configuration anyway.
=> JAVA-9127 update task registration to never be up to date

maven-plugin/pom.xml
I think the only thing we need to do to get the release to work is keep this `SNAPSHOT` version here. I'm going to try to release the plugin again. Worst case scenario it fails, best case scenario the existing build stuff auto strips the `SNAPSHOT` and updates the version on its own, which is I think what it's supposed to do. 🤞
=> JAVA-8421 update maven release version
