pom.xml
src/main/java/com/contrastsecurity/sdk/ContrastSDK.java
src/main/java/com/contrastsecurity/utils/ContrastSDKUtils.java
src/test/java/com/contrastsecurity/ScreenerTest.java

Fixed the https issue in Jenkins

Contrast 9693 v2

---

pom.xml
src/main/java/com/contrastsecurity/http/TraceFilterForm.java
src/main/java/com/contrastsecurity/http/UrlBuilder.java
src/main/java/com/contrastsecurity/sdk/ContrastSDK.java

Added Org traces without Application Id endpoint

CONTRAST-12739

---

src/main/java/com/contrastsecurity/http/TraceFilterForm.java
src/main/java/com/contrastsecurity/http/UrlBuilder.java
src/test/java/com/contrastsecurity/UrlBuilderTest.java

This was my first swing at the problem as I understood it. Let's chat if I'm heading in the wrong direction.

CONTRAST-19000 Encode tags when generating URLs

---

src/main/java/com/contrastsecurity/sdk/ContrastSDK.java
src/test/java/com/contrastsecurity/ContrastSDKTest.java
src/test/java/com/contrastsecurity/ScreenerTest.java

Contrast 21352 add proxy support

---

src/main/java/com/contrastsecurity/http/TraceFilterForm.java
src/main/java/com/contrastsecurity/http/UrlBuilder.java
src/main/java/com/contrastsecurity/models/Application.java
src/main/java/com/contrastsecurity/models/AssessLicenseOverview.java
src/main/java/com/contrastsecurity/models/LibraryScores.java
src/main/java/com/contrastsecurity/models/LibraryStats.java
src/main/java/com/contrastsecurity/models/VulnerabilityTrend.java
src/main/java/com/contrastsecurity/sdk/ContrastSDK.java

Adding Tags to Application model so can be retrieved with getApplication.

Adding Tags to Application model so can be retrieved with getApplication.

---

src/main/java/com/contrastsecurity/http/UrlBuilder.java
src/main/java/com/contrastsecurity/sdk/ContrastSDK.java

Regions specific changes for only getting licensed application data

Adding code to get licensed applications only, as opposed to all apps

---

src/main/java/com/contrastsecurity/models/Library.java

Deserialize the `high_vulnerabilities` value in the response.

Add ability to get high vuln count from libs

---

src/main/java/com/contrastsecurity/http/UrlBuilder.java
src/main/java/com/contrastsecurity/models/MetadataFilterGroup.java
src/main/java/com/contrastsecurity/models/MetadataFilterResponse.java
src/main/java/com/contrastsecurity/models/MetadataFilterValue.java
src/main/java/com/contrastsecurity/models/TagsResponse.java
src/main/java/com/contrastsecurity/models/TraceNoteResource.java
src/main/java/com/contrastsecurity/models/TraceNotesResponse.java
src/main/java/com/contrastsecurity/models/dtm/AttestationCreateRequest.java
src/main/java/com/contrastsecurity/sdk/ContrastSDK.java

Various changes for scripts written for Regions Bank as described in the title.

Adding functions for getting session metadata, assess tags for applications, get vuln trends, and generate attestation reports

---

src/main/java/com/contrastsecurity/models/dtm/ApplicationCreateRequest.java

Update casing for integration create request
Endpoints are snake_case

CONTRAST-39758 update integration create request casing

---

pom.xml
src/main/java/com/contrastsecurity/http/SecurityCheckForm.java
src/main/java/com/contrastsecurity/http/UrlBuilder.java
src/main/java/com/contrastsecurity/models/ApplicationImportance.java
src/main/java/com/contrastsecurity/models/JobOutcomePolicy.java
src/main/java/com/contrastsecurity/models/JobOutcomePolicySeverity.java
src/main/java/com/contrastsecurity/models/MetadataEntity.java
src/main/java/com/contrastsecurity/models/PointOfContactMetadata.java
src/main/java/com/contrastsecurity/models/SecurityCheck.java
src/main/java/com/contrastsecurity/sdk/ContrastSDK.java
src/test/java/com/contrastsecurity/ContrastSDKTest.java

Prepare for job outcome policy release

Contrast 39400 jop

---

src/main/java/com/contrastsecurity/http/UrlBuilder.java
src/main/java/com/contrastsecurity/models/RouteCoverageBySessionIDAndMetadataRequest.java
src/main/java/com/contrastsecurity/models/RouteCoverageMetadataLabelValues.java
src/main/java/com/contrastsecurity/sdk/ContrastSDK.java

This is related to my previous pull request #59, not sure why I missed adding these changes.  I think because I re-typed the changes manually and missed a part of them.

Adding missing changes for getting route coverage with session metadata

---

.github/workflows/build.yml
.gitignore
.mvn/wrapper/MavenWrapperDownloader.java
.mvn/wrapper/maven-wrapper.properties
.travis.yml
README.md
mvnw
mvnw.cmd

* Introduces Maven Wrapper to pin Maven at version 3.8.1
* Updates README to include Maven Wrapper
* Updates README to lead users to Maven Central instead of building the project locally
* Replaces Travis CI with GitHub Actions

👷 JAVA-3134 Replace Travis CI with GitHub Actions

---

src/main/java/com/contrastsecurity/http/RequestConstants.java
src/main/java/com/contrastsecurity/sdk/ContrastSDK.java

Update the headers to not be filtered out by ngix

Int 732 update headers

---

.gitignore

Add vscode specific files to gitignore

added vscode specific settings files to gitignore

---

pom.xml
src/main/java/com/contrastsecurity/http/IntegrationName.java
src/test/java/com/contrastsecurity/ContrastSDKTest.java

Int 738 fix pendo events

---

README.md

Update link in the README. The current one 404s.

Fix API documentation URL

---

.github/workflows/build.yml

Run build on pull requests so it's easier to verify changes.

Run build on pull requests

---

src/main/java/com/contrastsecurity/models/Rules.java

Add support for languages in the rules API.

Add support for rule languages

---

src/main/java/com/contrastsecurity/models/Rules.java

apply spotless formatting

---

src/main/java/com/contrastsecurity/http/ServerFilterForm.java

Add support for server quick filters when calling the server filter API.

Add support for server quick filters

---

src/main/java/com/contrastsecurity/models/Server.java

Add support for `latest_agent_version` field for servers.

Add support for latest agent version

---

src/main/java/com/contrastsecurity/models/Server.java

Adds Latest Agent Version and Out of Date for server

CONTRIBUTION - add support for latest agent version and out of date

---

src/main/java/com/contrastsecurity/models/Library.java
src/main/java/com/contrastsecurity/models/Vulnerability.java

This adds support for vulns in library responses when expanding on `vulns`.

Add support for vulns in library reponses

---

src/main/java/com/contrastsecurity/http/LibraryFilterForm.java

This adds the ability to expand servers on libraries. Previously servers were expanded when expanding apps but now an additional expansion was added for servers.

Support expanding servers for libraries

---

src/main/java/com/contrastsecurity/models/AssessLicenseOverview.java

Add `unused` and `max_expiration_date` to the license details.

Add unused and max expiration date

---

src/main/java/com/contrastsecurity/http/UrlBuilder.java
src/main/java/com/contrastsecurity/models/GlobalProperties.java
src/main/java/com/contrastsecurity/sdk/ContrastSDK.java

Add a method to get the global properties from TeamServer.

Add method to get global properties

---

.mvn/wrapper/maven-wrapper.properties
mvnw
mvnw.cmd
pom.xml
src/main/java/com/contrastsecurity/exceptions/ContrastException.java
src/main/java/com/contrastsecurity/exceptions/HttpResponseException.java
src/main/java/com/contrastsecurity/exceptions/ServerResponseException.java
src/main/java/com/contrastsecurity/models/ScanPagedResult.java
src/main/java/com/contrastsecurity/sdk/UserAgentProduct.java
src/main/java/com/contrastsecurity/sdk/internal/GsonFactory.java
src/main/java/com/contrastsecurity/sdk/internal/URIBuilder.java
src/main/java/com/contrastsecurity/sdk/scan/CodeArtifact.java
src/main/java/com/contrastsecurity/sdk/scan/CodeArtifactInner.java
src/main/java/com/contrastsecurity/sdk/scan/Project.java
src/main/java/com/contrastsecurity/sdk/scan/ProjectCreate.java
src/main/java/com/contrastsecurity/sdk/scan/ProjectInner.java
src/main/java/com/contrastsecurity/sdk/scan/ProjectsQuery.java
src/main/java/com/contrastsecurity/sdk/scan/Scan.java
src/main/java/com/contrastsecurity/sdk/scan/ScanCreate.java
src/main/java/com/contrastsecurity/sdk/scan/ScanException.java
src/main/java/com/contrastsecurity/sdk/scan/ScanInner.java
src/main/java/com/contrastsecurity/sdk/scan/ScanManager.java
src/main/java/com/contrastsecurity/sdk/scan/ScanPagedResult.java
src/main/java/com/contrastsecurity/sdk/scan/ScanSummary.java
src/main/java/com/contrastsecurity/sdk/scan/ScanSummaryInner.java
src/test/java/com/contrastsecurity/EqualsAndHashcodeContract.java
src/test/java/com/contrastsecurity/sdk/scan/ScansImplTest.java

Upgrade Spotless and Google Java Format to apply the latest style standards. As usual, the configuration change and formatting application are in two separate commits so that developers with branches can follow our guide [What to do with your branch when someone formats the whole source tree](https://contrast.atlassian.net/wiki/spaces/JAVA/pages/2310439172/Java+Code+Conventions#What-to-do-with-your-branch-when-someone-reformats-the-whole-source-tree).

🎨 JAVA-4928 Upgrade Google Java Format

---

pom.xml
src/main/java/com/contrastsecurity/http/TraceFilterForm.java
src/test/java/com/contrastsecurity/http/TraceFilterFormTest.java
src/test/java/com/contrastsecurity/http/UrlBuilderTest.java

Fixed Status adding new flags for tracked and untracked

TS-18990 Fix Tracked and Untracked Filters on Contrast SDK Java Library

---

gradle-plugin/src/main/java/com/contrastsecurity/gradle/plugin/ContrastGradlePlugin.java
gradle-plugin/src/main/java/com/contrastsecurity/gradle/plugin/ContrastVerifyTestTask.java
gradle-plugin/src/main/java/com/contrastsecurity/gradle/plugin/extensions/ContrastConfigurationExtension.java
gradle-plugin/src/test/java/com/contrastsecurity/gradle/plugin/GradlePluginTests.java

Pulls Test results from TeamServer and fails the build if any traces are found which exceed or meet the min severity.

Java 3779 fail builds based on ts results

---

gradle-plugin/README.md

I noticed the README was out of date, might as well update that now while we wait on gradle release things

JAVA-8606 update README for gradle plugin

---

.github/workflows/publish-gradle-plugin.yml
.github/workflows/publish-maven-plugin.yml
.github/workflows/publish-sdk.yml
gradle-plugin/build.gradle
gradle-plugin/src/main/java/com/contrastsecurity/gradle/plugin/ContrastVerifyTestTask.java
gradle-plugin/src/test/java/com/contrastsecurity/gradle/plugin/ConfigurationTests.java
gradle-plugin/src/test/java/com/contrastsecurity/gradle/plugin/util/ConfigurationExtensionValues.java

Workflow for releasing the plugin to the Gradle Plugin Portal

Java 8606 gradle release action

---

.github/workflows/publish-gradle-plugin.yml

JAVA-8606 update action

---

.github/workflows/publish-maven-plugin.yml

update Workflow to avoid pushing changes to main when doing the release

JAVA-8421 pushChanges=false

---

.github/workflows/deploy-from-manual-branch.yml

add manual release branch workflow

Java 8421 manual release workflow

---

.github/workflows/manual.yml

JAVA-8421 manual workflow for workflow testing

---

maven-plugin/pom.xml

Release candidate 2.13.3

---

maven-plugin/src/site/markdown/usage.md

Realized we missed some asks in this ticket - I think I've covered them in this PR

JAVA-8421 :pencil: Add some additional docs
